server:
  port: 7878
---
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/music?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
